apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-network-policy
  namespace: prod-front
spec:
  podSelector:
    matchLabels:
      app: filma-front
  policyTypes:
    - Ingress
    - Egress

  ingress: # 들어오는 트래픽
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: controller # 인그레스로 들어오는 트래픽 허용

      ports:
        - protocol: TCP
          port: 3000 # 프론트엔드 컨테이너 포트
  egress: # 나가는 트래픽
    - {} # 모든 트래픽 허용