apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    app: filma-back
spec:
  type: ClusterIP
  selector:
    app: filma-back
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000