apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
  labels:
    app : filma-back
spec:
  replicas: {{ .Values.replicas }} # 설정 파일로 관리
  selector:
    matchLabels:
      app: filma-back
  # progressDeadlineSeconds: 60 # 60초 동안 배포 실패하면 전체 실패 처리
  template:
    metadata:
      labels:
        app: filma-back
    spec:
      topologySpreadConstraints: # 토폴리지 분배 제약 조건
        - maxSkew: 1 # 최대 차이 1개
          topologyKey: kubernetes.io/hostname # 노드 이름을 기준
          whenUnsatisfiable: DoNotSchedule # 조건에 안 맞으면 배포 금지
          labelSelector:
            matchLabels:
              app: filma-back
      containers:
      - name: filma-back
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: POSTGRES_SERVER # 데이터베이스 서비스 경로
            value: "kakamu-data-postgresql-primary.data.svc.cluster.local"
          - name: POSTGRES_PORT # 포트
            value: "5432"
          - name: POSTGRES_USER # db 유저명
            value: "kakamu"
          - name: POSTGRES_DB # 데이터베이스 이름
            value: "kakamu"
          - name: POSTGRES_PASSWORD # 비밀번호는 secret 리소스로 참조
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: password

          - name: REDIS_HOST
            value: "redis-service.data.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            value: ""
          - name: REDIS_URL # 배포된 redis 서비스
            value: "redis://redis-service.data.svc.cluster.local"

          - name: DATABASE_URL
            value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_SERVER):$(POSTGRES_PORT)/$(POSTGRES_DB)"
          - name: FIREBASE_CONFIG_PATH # firebase 키 환경 변수
            value: "/app/auth/firebase-key.json"

          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "alloy.monitoring.svc.cluster.local:4317"

          - name: ML_API_BASE_URL
            value: "http://movie-service.data.svc.cluster.local:8080/chat-api"

          - name: APP_ENV
            value: "dev"
        volumeMounts:
          - name: firebase-key-volume
            mountPath: /app/auth
            readOnly: true

        ports:
          - containerPort: 8000 # fastapi 기본 포트

#        startupProbe: # 배포 실패 처리 테스트용
#          httpGet:
#            path: /no-path-test
#            port: 80
#          failureThreshold: 2 # 2번
#          periodSeconds: 5 # 5초마다

        readinessProbe: # 준비성 프로브, 실패 시 트래픽 차단
          httpGet:
            path: /db-test # db 검사 엔드포인트
            port: 8000
          initialDelaySeconds: 10 # 10초 있다가 검사 시작
          periodSeconds: 10 # 10초마다 재검사
          timeoutSeconds: 3
          failureThreshold: 3 # 3번 연속 실패 시 트래픽 차단

        livenessProbe: # 활성 프로브, 실패 시 pod 재시작
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3

      volumes:
        - name: firebase-key-volume
          secret:
            secretName: firebase-secret # 생성된 실제 시크릿 이름


