apiVersion: v1
kind: PersistentVolume
metadata:
  name: movie-pv
spec:
  capacity:
    storage: "10Gi" # 10 기가
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/home/ubuntu/movie" # VM에 실제로 존재해야함.
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master1