apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubeflow/manifests//common/kubeflow-roles/base?ref=26.03 # c-role 생성
  - https://github.com/kubeflow/manifests//common/istio/kubeflow-istio-resources/base?ref=26.03

  # central dashboard
  - https://github.com/kubeflow/manifests//applications/centraldashboard/overlays/oauth2-proxy?ref=26.03

  # profiles
  - https://github.com/kubeflow/manifests//applications/profiles/upstream/overlays/kubeflow?ref=26.03

  # admission webhook
  - https://github.com/kubeflow/manifests//applications/admission-webhook/upstream/overlays/cert-manager?ref=26.03

  # notebooks
  - https://github.com/kubeflow/manifests//applications/jupyter/notebook-controller/upstream/overlays/kubeflow?ref=26.03
  - https://github.com/kubeflow/manifests//applications/jupyter/jupyter-web-app/upstream/overlays/istio?ref=26.03

  # tensorboard
  - https://github.com/kubeflow/manifests//applications/tensorboard/tensorboard-controller/upstream/overlays/kubeflow?ref=26.03
  - https://github.com/kubeflow/manifests//applications/tensorboard/tensorboards-web-app/upstream/overlays/istio?ref=26.03

  # volumes
  - https://github.com/kubeflow/manifests//applications/volumes-web-app/upstream/overlays/istio?ref=26.03

  # katib
  - https://github.com/kubeflow/manifests//applications/katib/upstream/installs/katib-with-kubeflow?ref=26.03

  # pipelines
  - https://github.com/kubeflow/manifests//applications/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user?ref=26.03

patches:
  - path: patch-secure-cookies.yaml
  - path: patch-gpu-toleration.yaml
  - path: patch-mysql-controlplane.yaml
#  - path: patch-volume-web-rewrite.yaml