apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - https://github.com/kubeflow/manifests//common/istio/kubeflow-istio-resources/base?ref=26.03

  # central dashboard
  - https://github.com/kubeflow/manifests//applications/dashboard/upstream/centraldashboard/overlays/oauth2-proxy?ref=26.03

  # admission webhook
  - https://github.com/kubeflow/manifests//applications/dashboard/upstream/poddefaults-webhooks/overlays/cert-manager?ref=26.03

  # notebook controller / web app
  - https://github.com/kubeflow/manifests//applications/notebooks-v1/upstream/notebook-controller/overlays/kubeflow?ref=26.03
  - https://github.com/kubeflow/manifests//applications/notebooks-v1/upstream/jupyter-web-app/overlays/istio?ref=26.03

  # tensorboard
  - https://github.com/kubeflow/manifests//applications/notebooks-v1/upstream/tensorboard-controller/overlays/kubeflow?ref=26.03
  - https://github.com/kubeflow/manifests//applications/notebooks-v1/upstream/tensorboards-web-app/overlays/istio?ref=26.03

  # volumes
  - https://github.com/kubeflow/manifests//applications/notebooks-v1/upstream/volumes-web-app/overlays/istio?ref=26.03

  # katib
  - https://github.com/kubeflow/manifests//applications/katib/upstream/installs/katib-with-kubeflow?ref=26.03

  # pipelines
  - https://github.com/kubeflow/manifests//applications/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user?ref=26.03

patches:
  - path: patch-secure-cookies.yaml # http 적용
  - path: patch-gpu-toleration.yaml # 톨러레이션 적용 (gpu 노드에 배치)