apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubeflow

spec:
  template:
    spec:
      nodeSelector:
        gpu: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule