apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kakamu-dev-back
  namespace: argo
  annotations: # 알림 설정
    notifications.argoproj.io/subscribe.on-sync-failed.discord: "" # 실패
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: "" # 성공
spec:
  project: dev # project dev로 변경
  source:
    repoURL: https://github.com/kakao4-KAKAMU/kakamu_helm.git
    targetRevision: dev # dev로 변경
    path: charts/back-chart
    helm:
      valueFiles:
        - ../../environments/dev/back/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-back
  ignoreDifferences: #
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas # Hpa가 변경하는 replica 는 무시
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # 네임스페이스 자동 생성
      # - Replace=true          # 꼬인 리소스 무조건 덮어쓰기
      - Validate=false        # 스키마 검증 생략 (속도 향상 및 에러 방지)