apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kakamu-dev-platform
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: dev # project dev로 변경
  source:
    repoURL: https://github.com/kakao4-KAKAMU/kakamu_helm.git
    targetRevision: main
    path: platform/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argo # 실제 존재하는 네임스페이스, 리소스에 적용되는 건 metadata.namespace로 적용됨
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
