{{- if and (not .Values.argocd.enabled) .Values.neo4j.enabled }}
{{- $password := include "neo4j-chart.postgresqlPassword" . -}}
{{- if $password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.apocJdbcSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  URL: {{ include "neo4j-chart.apocJdbcUrl" . | quote }}
{{- end }}
{{- end }}
