apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-root
  namespace: argo
spec:
  project: dev # dev 프로젝트로 적용
  source:
    repoURL: https://github.com/kakao4-KAKAMU/kakamu_helm.git
    targetRevision: dev #  dev 브랜치 기준
    path: argocd/apps/dev # dev 관련 애플리케이션만 배포
    directory:
      recurse: true # 하위 디렉토리 탐색
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
