apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kakamu-root
  namespace: argo
spec:
  project: default # 나중에 prod project 생성 후 적용 필요
  source:
    repoURL: https://github.com/kakao4-KAKAMU/kakamu_helm.git
    targetRevision: main # main 브랜치 (prod 환경)
    path: argocd/apps/prod
    directory:
      recurse: true # 하위 디렉토리 탐색
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
