apiVersion: v1
kind: PersistentVolume
metadata:
  name: katib-mysql-pv # PV 이름
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage" # Default 스토리지 클래스로 자동 지정 됨.
  local:
    path: /mnt/data/katib-mysql # 노드에 실제로 만들어야 함.
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker3