apiVersion: v1
kind: LimitRange
metadata:
  name: dev-back-limit
  namespace: dev-back
  labels:
    env: dev
spec:
  limits:
  - type: Container # 컨테이너 기준
    default: # 최대 제한
      cpu: "500m"
      memory: "512Mi"
    defaultRequest: # 기본 요청
      cpu: "150m" # 150 으로 조절
      memory: "256Mi" # 256으로 조절

