apiVersion: v1
kind: LimitRange
metadata:
  name: dev-front-limit
  namespace: dev-front
  labels:
    env: dev
spec:
  limits:
  - type: Container # 컨테이너 기준
    default: # 최대 제한
      cpu: "500m"
      memory: "512Mi"
    defaultRequest: # 기본 요청
      cpu: "50m"
      memory: "128Mi"

