apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubeflow/manifests//common/istio/istio-install/base?ref=26.03

# gpu 노드에 배치 허용
patches:
  - path: patch-istio-toleration.yaml