apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "2" # 애플리케이션 생성 순서

spec:
  project: default

  source: # overlays 구조로 전환
    repoURL: https://github.com/kakao4-KAKAMU/kakamu_helm.git
    targetRevision: feat/kubeflow
    path: argocd/apps/overlays/istio-gpu

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
