apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "2" # 애플리케이션 생성 순서

spec:
  project: default

  source:
    repoURL: https://github.com/kubeflow/manifests.git # kubeflow 공식 깃허브 주소
    targetRevision: "26.03" # 태그
    path: common/istio/istio-install/base

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

# Pod가 어느 노드에도 배치되지 못함
# 1개는 테인트 (컨트롤 플레인)
# 3개는 리소스 부족
# overlays 구조로 전환 필요.