apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-kserve
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "6" # 애플리케이션 생성 순서

spec:
  project: default

  source:
    repoURL: https://github.com/kubeflow/manifests.git # kubeflow 공식 깃허브 주소
    targetRevision: "26.03" # 태그
    path: applications/kserve/kserve

  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true