apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kakamu-neo4j
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: shared
  source:
    repoURL: https://github.com/kakao4-KAKAMU/kakamu_helm.git
    targetRevision: main
    path: charts/neo4j-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
