postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest # latest 태그지만 digest(sha)으로 고정, 버전 확인 결과 18.3
    digest: sha256:8ee67b02aa9d8d0932b7215b6b0cdd418e87caa324a34ebefef1742737aa2400 
  architecture: replication

  auth:
    username: kakamu
    database: kakamu
    existingSecret: postgresql-secret # db 비밀번호 저장된 secret
    secretKeys:
      userPasswordKey: password  # primary 키
      replicationPasswordKey: replication-password # replica 키

  primary:
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "1000"
    nodeSelector:
      kubernetes.io/hostname: master1
    tolerations: # 컨트롤 플레인에 배치 하기 위한 톨러레이션
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    persistence:
      enabled: true
      storageClass: local-storage
      size: 20Gi
      selector:
        matchLabels:
          role: primary

    resources: # 리소스 확인 후 조정 필요
      requests:
        cpu: "1"
        memory: "2Gi"
      limits: {}


  readReplicas:
    replicaCount: 1

    nodeSelector:
      kubernetes.io/hostname: worker3

    persistence:
      enabled: true
      storageClass: local-storage
      size: 20Gi
      selector:
        matchLabels:
          role: replica

    resources: # 리소스 확인 후 조정 필요
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"