pgbouncer:
  enabled: true
  image:
    registry: docker.io
    repository: edoburu/pgbouncer
    tag: latest
    digest: ""
    pullPolicy: IfNotPresent
  replicaCount: 1
  listenAddr: "0.0.0.0"
  port: 6432
  postgresql:
    host: "" # 비어 있으면 {release-name}-postgresql-primary 사용
    port: 5432
  authType: scram-sha-256 # Bitnami PostgreSQL 기본 인증 방식
  poolMode: transaction
  serverResetQuery: "DISCARD ALL"
  maxClientConn: 1500
  defaultPoolSize: 250
  minPoolSize: 200
  reservePoolSize: 50
  reservePoolTimeout: 3
  maxDbConnections: 300
  serverIdleTimeout: 60
  serverLifetime: 3600
  queryWaitTimeout: 20

  nodeSelector:
    kubernetes.io/hostname: master1
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  extraEnv: []

postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest # latest 태그지만 digest(sha)으로 고정, 버전 확인 결과 18.3
    digest: sha256:8ee67b02aa9d8d0932b7215b6b0cdd418e87caa324a34ebefef1742737aa2400 
  architecture: replication

  auth:
    username: kakamu
    database: kakamu
    existingSecret: postgresql-secret # db 비밀번호 저장된 secret
    secretKeys:
      userPasswordKey: password  # primary 키
      replicationPasswordKey: replication-password # replica 키

  primary:
    nodeSelector:
      kubernetes.io/hostname: master1
    tolerations: # 컨트롤 플레인에 배치 하기 위한 톨러레이션
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    persistence:
      enabled: true
      storageClass: local-storage
      size: 20Gi
      selector:
        matchLabels:
          role: primary
    extendedConfiguration: |
      max_connections = 350
      
      shared_buffers = 5GB
      effective_cache_size = 14GB
      maintenance_work_mem = 2GB
      work_mem = 16MB
      wal_buffers = 64MB

      min_wal_size = 2GB
      max_wal_size = 8GB
      checkpoint_completion_target = 0.9
      checkpoint_timeout = 15min

      random_page_cost = 1.1
      effective_io_concurrency = 1000

      max_worker_processes = 32
      max_parallel_workers = 16
      max_parallel_workers_per_gather = 2
      max_parallel_maintenance_workers = 4

      autovacuum_max_workers = 6
      autovacuum_vacuum_threshold = 20
      autovacuum_naptime = 5s
      autovacuum_vacuum_cost_limit = 2000

      idle_in_transaction_session_timeout = 60s
      statement_timeout = 60s
      lock_timeout = 5s
      deadlock_timeout = 5s
      log_lock_waits = on

    resources: # 리소스 확인 후 조정 필요
      requests:
        cpu: "1"
        memory: "2Gi"
      limits: {}


  readReplicas:
    replicaCount: 1

    nodeSelector:
      kubernetes.io/hostname: worker3

    persistence:
      enabled: true
      storageClass: local-storage
      size: 20Gi
      selector:
        matchLabels:
          role: replica

    resources: # 리소스 확인 후 조정 필요
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"