apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: master1
      tolerations: # 컨트롤 플레인에 배치할 톨러레이션
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: redis
          image: redis:7-alpine # 경량화 이미지
          command: ["redis-server", "--protected-mode", "no"]
          ports:
          - containerPort: 6379 # 컨테이너 포트
            name: redis
          resources: # 리소스 제한
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
