apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  type: ClusterIP
  selector:
    app: vllm
  ports:
  - name: vllm-port
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: vllm-embed-port
    protocol: TCP
    port: 8001
    targetPort: 8001