apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # 모델 크기에 맞춰 여유롭게 설정 (Llama3 8B는 약 15GB